### ISSUE TITLE
Armature for GH2 PS2 models are severely warped on latest release version

### ISSUE THREAD

**Issue by MetricCepheid** [vidsicious612/hmx-importer#3]
Latest commit- [d95cd9d](https://github.com/vidsicious612/hmx-importer/commit/d95cd9da39cd79f2db1f71cdecbfa0b873a3dce9)
**ark\char\grim\og\gen\grim.milo_ps2**
![image](https://github.com/user-attachments/assets/c7b7f934-74b7-4b05-9f01-c67cef1ceb2c)

Earlier commit- [00a1264](https://github.com/vidsicious612/hmx-importer/commit/00a126427f3cb7819d9f5bbd6decad1c233b77f6)
**ark\char\grim\og\gen\grim.milo_ps2**
![image](https://github.com/user-attachments/assets/50e3909f-a21f-4fbb-9986-a29143bd686a)

**Comment by vidsicious612** [comment]
Hi, so bc of differences between how Blender and HMX games works, I had to make the bones import with the location + rotation in a way that you would pose an armature in Blender. So to fix the distorted issue, you'll have to apply the pose as rest pose.
