### ISSUE TITLE
Extra models and textures 

### ISSUE THREAD

**Issue by molnarnoah** [vidsicious612/hmx-importer#5]
It’s not an issue just a question. Is it possible especially for LRB to import character models from other Lego games with textures? If it’s possible it has to over write the original files or is it possible to add as a DLC. I mean like extra hairstyles, clothes, legs ect. Thank you for your answer?

P.S.: Awesome work bro keep it goin!🤙

**Comment by vidsicious612** [comment]
Thanks for the support.
I don't fully understand what you mean. Can you clarify further?

**Comment by vidsicious612** [comment]
Oh. Well Lego Avengers uses a different engine than the engine this script is written for. So, you'd have to find another script or figure out the format and make your own.
